[workspace]
resolver = "2"
members = ["crates/koca", "crates/cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.98"
# brush = { package = "brush-core", version = "=0.3.1" }
brush = { package = "brush-core", path = "../../hwittenborn/brush/brush-core" }
clap = { version = "4.5.37", features = ["derive", "env"] }
koca = { path = "crates/koca" }
thiserror = "2.0.12"
tokio = "1.45.0"
