[package]
name = "koca"
version.workspace = true
edition.workspace = true
description = "The Koca library"

[dependencies]
brush = { workspace = true }
brush-parser = { workspace = true }
itertools = "0.14.0"
thiserror = { workspace = true }
